### ISSUE TITLE
QuillzToxic and write permissions

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#137]
I'm really happy you just kicked me

[/sarcasm]

**Comment by The-QullzToxic** [comment]
![image](https://cloud.githubusercontent.com/assets/9355799/7236077/6fd94118-e78a-11e4-8553-9dc91a854471.png)

**Comment by GrannyCookies** [comment]
Who did that!?

**Comment by The-QullzToxic** [comment]
Idk
I was just about to do somthin aswel

**Comment by The-Cheese-Eater** [comment]
It was decided that it would be better for you to make changes in a separate repo, and then make a pull request when your code is reviewed.

**Comment by GrannyCookies** [comment]
Ah, okay @The-Cheese-Eater.

**Comment by The-QullzToxic** [comment]
My codes still here, It seems somthing with sgit was wrong :P (My Blog code) Can I request a update to the site?

**Comment by MegaApuTurkUltra** [comment]
Once we get CI set up maybe we can let quillz back in, but for now, the best way to prevent stuff like what happened from happening is with pull reqs. Sorry quillz.

**Comment by The-QullzToxic** [comment]
So my request to update the site is invalid, I want to test something, Oh wait nevermind you removed it all ready and are probably assigning someone else to do the job because I'm an idiot.

Still you guys have messed loads of code up before? Or do you hate me

**Comment by andrewjcole** [comment]
What? This isn't fair. Changes can always be reverted. Does he get a second chance? I'm not sure I want to be here anymore.

**Comment by The-Cheese-Eater** [comment]
You know full well that we do not hate you quillz, I've known you for a year by now. I have invited him back into the team because this project deserves not to get into disputes. However, Quillz must understand this there is a limit to the amount of chances I can give before people start getting annoyed at having to revert changes all the time. With respect @andrewjcole, but you were not zeus trying to scrape backups from the developer site to patch the mess. I am acting as a admin within this project, and I intend to keep it that way; becoming a negotiator to solve personal disputes is certainly not high upon my agenda.

I'm tired of all that grumpy bore I just wrote, shall we have some lightheartedness and positivity again? :)

**Comment by andrewjcole** [comment]
I typed that comment before I fully understood. I apologise. I'll think of this as a lesson for us all. However, please be respectful to Quillz. People do make mistakes.

**Comment by MegaApuTurkUltra** [comment]
@The-QullzToxic we removed you because you seriously screwed code up. I know you used the command line thing, and you're new at it, but that's not really an excuse. If you know you're bad at the command line git, you should have used a GUI-based git, especially on a critical project like OpenSprites. You can test command line git all you want on your own repos.

What you did was pretty bad. You deleted tons of our code, and apparently screwed up the blog layout or something.

We didn't mean to hate when we removed you from the organization. We just can't afford huge code-deletions and stuff in the future.

Just because you do not have write permissions to the repo does not mean you can't contribute. You can create your own fork, work there, and send a pull request when you're done. You can still comment on our issues and commits too. If you show that you can make significant changes and handle git responsibly in your fork, we'll give you write permissions back.

To be clear, you are not banned from the organization entirely. We want to be nice and give you a second chance, it's just that we can't give you write permissions at the moment, because of what happened.

I'm unlocking this issue so you can comment back if necessary, however please be respectful when commenting (ie, don't call yourself an idiot, don't accuse anyone of hate, and keep the sarcasm to a minimum).

**Comment by The-QullzToxic** [comment]
This is the second sweeggyest issue #137

**Comment by MegaApuTurkUltra** [comment]
Sorry, but if you don't have any legitimate comments, there's no reason to keep this open.
