### ISSUE TITLE
Implement sprite/script/media listing

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#140]
For example, the following links:
http://dev.opensprites.gwiddle.co.uk/sprites
http://dev.opensprites.gwiddle.co.uk/scripts
http://dev.opensprites.gwiddle.co.uk/media

**Comment by MegaApuTurkUltra** [comment]
Check this out: http://dev.opensprites.gwiddle.co.uk/site-api/list.php

One problem. Do we really want to be able to share entire sprite files, or make virtual collections of assets? Because the way I'm thinking about this is, we don't want duplicate files (waste of space), and my upload script already extracts out assets from sprite and project archives, so why not make "sprites" a virtual collection of assets that you can download in one bundle? It's kind of like how Scratch treats 2.0 projects.

If you see index.php, it reflects my ideas. I replaced it with lists of
 - Popular assets
 - Featured assets
 - Popular collections
 - Featured collections

I call the virtual organization of assets a "collection," but we could call it a "sprite" instead, if need be.

So what we should really rename the navbar tabs to are
 - Assets
 - Scripts
 - Collections

Thoughts?

**Comment by MegaApuTurkUltra** [comment]
Check out the front page: http://dev.opensprites.gwiddle.co.uk/

It's something, at least

**Comment by The-Cheese-Eater** [comment]
That API is pretty cool! That will be handy for creating that mod page I've always wanted. <3
