### ISSUE TITLE
We need some form of test site.

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#17]
...currently only Firedrake969 (the owner?) can upload to the alpha site.
It will be much easier if we could all (or some) could upload.

**Comment by The-Cheese-Eater** [comment]
Currently only Firedrake has admin access as well as me because he asked first, and he showed interest in to the project first. Unfortunately I can't give admin access to everyone because they will have access to the databases which will be storing emails and other data. I think I'll make a special FTP account for those who I deem trustworthy to edit the alpha site. In order to get the credentials, send a request to admin@opensprites.x10.mx. Thanks. :)

**Comment by GrannyCookies** [comment]
Oh, okay. Good idea with the FTP account.

**Comment by The-Cheese-Eater** [comment]
I've made the account. The FTP hostname is: ftp.opensprites.x10.mx The username is: developers@opensprites.x10.mx. For the password, send an email to admin@opensprites.x10.mx and I'll reply with it.

**Comment by GrannyCookies** [comment]
Email sent, thanks
