### ISSUE TITLE
Remove ajax.googleapis.com dependance

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#191]
[This](https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js) is fetched from Google in the Header.html file. Is this required - can we not host the file ourselves?

**Comment by liam4** [comment]
BUT CHEESEEATER
THAT WOULD MEAN ADDING 200 EXTRA KB OF DATA
WE CAN'T POSSIBLY SPARE THAT

**Comment by MegaApuTurkUltra** [comment]
We're not using ajax libs. It's literally just jquery :package:

**Comment by The-Cheese-Eater** [comment]
So... does that mean we still need to fetch that from Google?

**Comment by liam4** [comment]
Why are we using jQuery when `document.querySelector` works fine? :package:

**Comment by GrannyCookies** [comment]
Because jQuery is swaggy.

**Comment by GrannyCookies** [comment]
[**@The-Cheese-Eater**](https://github.com/The-Cheese-Eater) commented on [16 Nov 2015, 07:06 GMT](https://github.com/OpenSprites/OpenSprites/issues/191#issuecomment-156943155 "2015-11-16T07:06:55Z - Replied by Github Comment Enhancer"):
> So... does that mean we still need to fetch that from Google?

No, just download the file and stick it in includes/js, it's just because whoever first made Header.html couldn't be bothered to download it.

**Comment by liam4** [comment]
> Because jQuery is swaggy
so are promises

**Comment by The-Cheese-Eater** [comment]
@GrannyCookies Thanks, will do :P
