### ISSUE TITLE
Followers/Following

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#33]
I don't if we should have followers on the site or not. I don't want all this silly F4F stuff being transferred over to OS, but I don't want to take out key functionality. Perhaps we could rename it to 'subscribers' or something like that? I think the actual feature should just pop you a notification when the someone uploads something, and not have counts or lists. I think coding time could be spent elsewhere. What does everyone else think? Remove it altogether? Rename? Basic feature?

**Comment by Firedrake969** [comment]
Keep it as "following", but you only can see who you follow and can't see anything about anybody else's followers/following

**Comment by The-Cheese-Eater** [comment]
Righto, good idea. Lets see what everyone thinks.

**Comment by jayforsythe** [comment]
...definitely not "spritez"...

I like firedrake's idea

**Comment by The-Cheese-Eater** [comment]
Righto

**Comment by Firedrake969** [comment]
cool

**Comment by The-QullzToxic** [comment]
I think subscribers would be better. Instead of I subscribe it should say "More people you might like..." and only make it show a few at a time, Ultimately lowering the amount of F4F. Or even remove I`m subscribing, and make it simply make it "Oooh,  I like you let me subscribe to get notifications". (Can I join front end pl0x)

**Comment by Rumanti** [comment]
My opinion: Remove "who is following me", "who is following them", and "how many followers" definitely. The "who is following me" feature is competitive, since some peoples brag when certain Scratchers follow them. Same with "who is following them". And many peoples Follow4Follow because the last feature I mentioned, "how many followers". This features should be removed **completely**, not just marked it private or move it somewhere else like what the Scratch Team did. But the "how many I'm following" and "who I'm following" feature should be kept, but private. And I don't think renaming it to "suscribe" would solve the problem. (f4f in Scratch is sub4sub in YouTube, I think)

**Comment by The-Cheese-Eater** [comment]
That's a good point there, I think following should just be kept as a news feed feature, and not as a social feature like Scratch.

**Comment by liam4** [comment]
Perhaps (I don't know if this would work) add an RSS feed for each user so that people can simply subscribe to it in their bookmarks bar?

**Comment by jayforsythe** [comment]
Actually, to be honest, I doubt there will be more than 40 or 50 people (70 tops) on the site, so I think it's gonna be fine to leave it like Scratch. Besides, if someone's going to go on a resource sharing site, it's likely they actually make good projects and don't do all the F4F mess.

**Comment by Rumanti** [comment]
@jayforsythe I agree with all of them, but uncertain on the first one. You have good points, but I still think that it's better to remove the features I mentioned. What advantages would OS have if we have these features? And although the chance is insanely small, there's still a risk. (excuse me for hating fame trading so much). But, again, you have good points.

**Comment by pilppe** [comment]
@Rumanti the main advantage would be that people with the most follows and popular sprites could be the ones with the highest quality, so if people want good quality they can just easily put "Most follows" and see their collection.

**Comment by Firedrake969** [comment]
It'd also be easiest to code doing the way I said...
and I'll probably be the one coding it xD

**Comment by andrewjcole** [comment]
@Firedrake969 Maybe we'll have more PHP people by then. I dunno. :stuck_out_tongue: I currently am figuring out locally testing PHP on Linux.

**Comment by Firedrake969** [comment]
nah, it's fine - I like PHP :P

**Comment by zappy1333** [comment]
I think it should be changed to "subscribe" and it's jut for notifications. Also nobody else can see who you are subscribed to or vice versa.
