### ISSUE TITLE
Open source website

### ISSUE THREAD

**Issue by zappy1333** [OpenSprites/OpenSprites#50]
Just wondering, is it OK to have an open source website?
Because PHP manages private info like passwords, so wouldn't having it be open source make it easier for people to get peoples passwords or something
Sorry if this is a silly question...

**Comment by andrewjcole** [comment]
Not really unless they had access to the database, but I guess it would make security flaws more findable for hackers.

**Comment by pilppe** [comment]
We have an database, they are not gonna access them.

We are living in 2015, open-source is the way to go. There will be no MySQL injections etc. if we just use PDO instead of MySQLi.

Also, when its open-source everyone can access the code and fix security flaws that they find. Thats why its amazing.

Did open-source make Linux worse? Nope.

**Comment by The-Cheese-Eater** [comment]
BitCoin is Open Source.

**Comment by pilppe** [comment]
Yep.

https://github.com/bitcoin/bitcoin 

And Bitcoin is soon on ATM's. So im pretty sure Open-source is safe. No need to worry.

**Comment by Firedrake969** [comment]
Using PDO doesn't proof us against SQL injections. 

It's fine.

**Comment by zappy1333** [comment]
OK, thanks!
