### ISSUE TITLE
We need a more organised task list!

### ISSUE THREAD

**Issue by DM5555** [OpenSprites/OpenSprites#71]

**Comment by The-QullzToxic** [comment]
We indeedy do

**Comment by The-Cheese-Eater** [comment]
Yes, indeed we do. We all mostly seem to have an idea of what to do, though.

**Comment by The-QullzToxic** [comment]
We do? https://www.youtube.com/watch?v=HfdCq4dgRHo

**Comment by DM5555** [comment]
I am getting really bored right now, must do some JS

**Comment by DM5555** [comment]
I wanna make a script that proscesses a project

**Comment by DM5555** [comment]
The JSON that is

**Comment by The-Cheese-Eater** [comment]
Why would you need to process a project? I don't have any plans for uploading via projects, it almost defeats the aim of this site.

**Comment by DM5555** [comment]
It could be for uploading

**Comment by DM5555** [comment]
You upload a projct and you choose what sprite you want and wether to keep the variables, etc

**Comment by The-Cheese-Eater** [comment]
I guess it could be used as extra functionality, but I don't want it to be the main uploading system.

**Comment by The-QullzToxic** [comment]
Well, unuploaded projects might be cool

**Comment by The-QullzToxic** [comment]
Me and my butter fingers....

**Comment by DM5555** [comment]
What do we need to do then?

**Comment by The-Cheese-Eater** [comment]
We need a homepage, at the moment it is plain and dull. I'm sure you can exercise your JavaScript skills there.

**Comment by DM5555** [comment]
Any suggestions?

**Comment by DM5555** [comment]
Wait

**Comment by DM5555** [comment]
IDEA

**Comment by DM5555** [comment]
Theme button?

**Comment by The-QullzToxic** [comment]
I wish github was live coding. And no theme button... No Theme button!

**Comment by The-Cheese-Eater** [comment]
I like a theme button; the current theme, and a dark theme?

**Comment by The-QullzToxic** [comment]
I guess, Maybe a night theme

**Comment by The-Cheese-Eater** [comment]
OpenSprites Classic, OpenSprites Light, OpenSprites Terminal (terminal is dark with terminal like fonts (see DuckDuckGo).

**Comment by liam4** [comment]
I like the ideas, I want to make such ideas. ;3

**Comment by The-Cheese-Eater** [comment]
A theme that adjusts to the user's computer time preferences? Togglable, or course.

**Comment by The-QullzToxic** [comment]
Is the site ios readable?

**Comment by The-Cheese-Eater** [comment]
Perhaps you can @DM5555 DM could joint work on it @liam4? I think DM wants it to himself, though. :P

**Comment by The-Cheese-Eater** [comment]
Should be @The-QullzToxic

**Comment by The-Cheese-Eater** [comment]
I think the original site was, not sure about this one.

**Comment by The-QullzToxic** [comment]
I`ll check later. Any css/html work need doing?

**Comment by The-Cheese-Eater** [comment]
@DM5555 Would the theme switch just change the CSS properties, or link to another CSS file?

**Comment by liam4** [comment]
At the moment I need to work on fixing a but for my site though.

And sounds like a cool idea. Change the `href` of a `<link>` through JS?

```js
setInterval(function() {
  var time = new Date();
  if (time.insert_function_here) {
    document.getElementById("theme-link").href = "light";
  } else {
    document.getElementById("theme-link").href = "dark";
  }
});
```
or something.

**Comment by The-Cheese-Eater** [comment]
We need a main page @The-QullzToxic

**Comment by The-Cheese-Eater** [comment]
Sounds cool @liam4.

**Comment by The-QullzToxic** [comment]
Like a homepage?

**Comment by liam4** [comment]
@The-Cheese-Eater Yep. I'm going to fix a bug in my page so be right back. :P

**Comment by The-QullzToxic** [comment]
irc guys? To stop spammin things?

**Comment by liam4** [comment]
Sure, I'll get on. :P

**Comment by liam4** [comment]
I'm on.

**Comment by The-Cheese-Eater** [comment]
We just need content on the homepage @The-QullzToxic.
Righto @liam4.

**Comment by The-QullzToxic** [comment]
Irc Guy?

**Comment by pilppe** [comment]
Linux didnt have task lists :D

**Comment by liam4** [comment]
IRC. I'm on.

**Comment by liam4** [comment]
Hey @The-Cheese-Eater, you getting on IRC? :P

**Comment by The-Cheese-Eater** [comment]
yeah sure :package:

**Comment by bleush38p** [comment]
As far as I can tell, uploading from a project is the *entire* purpose of this site. If I've made a resource to be used in scratch, I should use it in scratch, it's like a token of authenticity. Did you see my counterarguments on your original response? I can't think of one reason it's not a good idea, and if you have any I'd love to address them. It would solve a nearly uncountable amount of issues. Additionally, I'm always very reluctant to create new accounts, or enter my password anywhere. Solves that. "Uploading" scripts? Solves that. Likes, stars, comments, whatever? Solves that.

**Comment by The-Cheese-Eater** [comment]
I feel that using the Scratch infrastructure to provide our media is cheating to be honest. If we rely on that, then all we are doing is providing a way Scratchers can search this media. If we wanted to do that, then I could have created a Scratch forum directory topic. :P I want to create a separate platform from Scratch, that doesn't have to go about fetching loads JSON from the Scratch site. Of course, uploading from projects could be added as a second option, but I wouldn't want it to be mainstream for the reasons above. Also, creating loads of projects for your uploads is a bit annoying, and I'm sure many of those 'professional' Scratchers wouldn't want to upload a project full of raw media straight to their account.

**Comment by andrewjcole** [comment]
@The-Cheese-Eater I agree completely.

**Comment by bleush38p** [comment]
Then they shouldn't be uploading a project like that. The point of this is not so people make large projects with media (and it's worth noting now that projects don't even have to be shared for this to work), but for resources to have to be *worthy* of OS in that they are built for scratch projects. This is Scratch resources, not freesounds, or clipart.com, although if you think it seems to be you should make it clear that this has nothing to do with Scratch; as it apparently doesn't.

And I'll mention again: how do you plan to upload and distribute scripts or custom blocks? Surely not by typing scratchblocks - what a *huge* PITA. Even the argument that there is a generator for that is invalid; WE can provide that, that's the whole point of this. Even more surely not by uploading a project, picking a script from that, then letting people download a project with the script in it. Imagine the server load - zipping and unzipping, parsing and generating - speaking of, that's what this idea does, but without all the extra fluff, thus in a fraction of the code. In addition, imagine getting one of those into a project - make a new project, upload the one you downloaded, add it to your backpack, delete the project, get it out of your backpack ... And by this point you've forgotten what the darn script even does.

Anyway, [/rant]. Feel free to come back after running out of server space, you've had multiple dropped requests and have overloaded the CPU/memory, and had a few DMCA notices.

**Comment by Firedrake969** [comment]
Maybe get it from a project and save the JSON to the server, so the project doesn't have to stay up?

**Comment by andrewjcole** [comment]
@bleush38p Happy thoughts :P

**Comment by The-Cheese-Eater** [comment]
I'm not trying to run a professional and polished setup here. Going into a project and sticking stuff in it to upload is a pain in the backside, for me anyway. However, I agree about uploading scripts and custom blocks. They WILL require access to the project/backpack. I'm more turned towards using the backpack really, because it's quicker than making a project. With this site, I aim to combine all of the utilities that those other 'free clip(whatever)' sites offer into a single site to make it a whole load easier for Scratchers to find things for their projects. Since our ToS will state that the only thing to be uploaded is USER GENERATED content licensed under the Creative Commons license, then a DMCA is extremely unlikely. I highly doubt the average 10 year old scratcher would file a costly DMCA for a jumping sprite script, would they? To be honest, I'm not to fussed about server load. I wouldn't imagine that a great amount of people would use the site all at the same time. Like the problems we have had on IRC, most people live in different timezones. In fact, there are scratchers in nearly every country in the world! It would be very unusual for more than 10 or 20 people to put in requests at the same time, because of time-zones, and sometimes it takes people a while to browse and choose! I would be fussed if I owned the server, but I don't so I don't mind if the CPU or Memory gets maxed out. That is also why we are looking to take on premium hosting within the next few months or so. By just making the site read all it's data from the Scratch website, is honestly not much of a challenge. We can challenge ourselves by working out an efficient algorithm for compression and decompression. Space and data transfer is not a problem either, since x10 don't cap data on the free version.

So overall, I do like the ability to fetch your own media from your backpack, because it doesn't require a specific project to upload from. Uploading scripts and custom blocks would of course require that feature, but other media uploads wouldn't so much, it could be provided as a convenience for you. :P I mean, if I have a sound I want to upload, I'd have to: Open browser > Go to Scratch > Open backpack through editor > Upload sound to project > Drag sound into backpack > close Scratch > Go to OpenSprites > Do OpenSprites things. It's a bit of a faf for something that would have taken less than ten seconds with a simple 'browse or drag here' button. :P

**Comment by zappy1333** [comment]
Just an idea, but there could be an OS Scratch extension- this would be like the backpack and it would allow you to easily drag sprites and scripts into it and upload them.
It could also allow you to easily get scripts and sprites from the OS website. Every upload could have a unique code- all you would need to do would be to type in the code and then drag it into the Scratch editor.

**Comment by pilppe** [comment]
@zappy1333 Thats actually a good idea. @MegaApuTurkUltra could implement that easily.

**Comment by The-Cheese-Eater** [comment]
That's a cool idea! It could be a Java app or something, so you wouldn't need to enter a browser.

**Comment by pilppe** [comment]
But, for this issue. Theres alot of open-source projects out there, there is no specific task to do. Just develop and soon it will become better. Report bugs, and over time it will be complete and the only thing thats left to do is bug fixing.

Now, we have IRC and IRC has been very good for us in the past few days. We should keep using it to keep track on what everyone is doing.

**Comment by Firedrake969** [comment]
No, use issues and commit descriptions.  I generally cannot connect to the IRC, so won't consult on it before changing things.

**Comment by The-Cheese-Eater** [comment]
Issues and comment descriptions are best for problems. IRC is good for discussing new features or general chat. This is off topic, closing.
