### ISSUE TITLE
Update the privacy policy

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#80]
As of commit 6b1862d, we are using google's CDN. Should it be in the Privacy Policy?

**Comment by The-Cheese-Eater** [comment]
Content Delivery Network? Its importing some JS from Google's API server. :P

**Comment by The-Cheese-Eater** [comment]
We also use Google fonts as well. I'll just write a paragraph on third party connections.

**Comment by Firedrake969** [comment]
I don't think so because it doesn't have to do with user data or cookies.

**Comment by The-QullzToxic** [comment]
I would want to know if what I was looking at was sending info to Google... Bacicly your feeding google D:

**Comment by The-Cheese-Eater** [comment]
Just because you are connecting to Google, it doesn't mean you are being tracked. Anyhow, you're being tracked using Google, or not. The UK's GCHQ government organization tracks ingoing and outgoing data from the UK, and also shares it with the NSA. It doesn't matter what a website's privacy policy is, you're getting tracked by somebody whether you like it or not.

**Comment by The-QullzToxic** [comment]
I personally don't mind governments as much as google. Governments use the information for security perposes

**Comment by The-Cheese-Eater** [comment]
But what is wrong is that the UK shares this info with the US. I believe there is/was some kind of review of that after an outcry?

**Comment by The-QullzToxic** [comment]
... *Goes to war*

**Comment by The-QullzToxic** [comment]
Don't vpns stop you from getting tracked by NSA and GCHQ

_Sent via Hubroid_
