### ISSUE TITLE
Completly detaching OS from scratch

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#82]
I think we should completely detach from scratch, so people can sign up on is to share all kinds of things, without needing a scratch account. You may question images, upload them to cube upload. I believe that OpenSprites should be detached from scratch, but still keep functions that are scratch orientated and muddle them up with other functions. By making this change we are aiming at a bigger market.

**Comment by GrannyCookies** [comment]
Support

**Comment by andrewjcole** [comment]
Custom spritesheets? :P

**Comment by The-QullzToxic** [comment]
This also could be useful to implement new features!

**Comment by Firedrake969** [comment]
I don't agree, since we are trying to cater to the Scratch community like Scratch Resources did.

**Comment by GrannyCookies** [comment]
@Firedrake969 We can still be oriented to Scratch users, but it would be helpful to people who don't use scratch too.

**Comment by The-Cheese-Eater** [comment]
"By making this change we are aiming at a bigger market." This isn't Microsoft, it's a small open-source project.

**Comment by The-Cheese-Eater** [comment]
I don't want to open up the site to the wider internet. That's when you start getting inappropriate and copyrighted content uploaded. I don't want this site to become an open-source dropbox thing, but a site to share content to specifically use in Scratch projects. You don't really suggest any benefits of separation, but there are a load of negatives. I think Scratch has a nice community, which I would like to see on this site. If the gates were opened to the wider internet, then all the whole range of internet weirdos would come flocking in, looking for a way to share copyrighted, or illegal content without facing consequences. The Scratch account verification limits the site to Scratchers who only need the content for personal/project use. If other internet users need content for their things, they can do a web-search. Bear in mind, that if we have a large user-base, then maintaining the site and security will become a challenge. I know for a fact, that we will need to moderate the site, and I'm going to limit moderation to a select group of developers who I deem trustworthy. 

TD;LR: I don't want to open the site up to any old Tom, Dick or Harry. It's closed for the private use of the Scratch user-base only.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Well, that was... big. /play secret

**Comment by GrannyCookies** [comment]
I was messing around with github emoji, see http://www.emoji-cheat-sheet.com/

**Comment by The-Cheese-Eater** [comment]
Ahh, I see. :P

**Comment by The-QullzToxic** [comment]
Sorry, If I seemed like I was Bill Gates (I'm doing a play, I'm Bill Gates :3) I just thought it would be a cool thing to do

**Comment by bleush38p** [comment]
> but a site to share content to specifically use in Scratch projects.

Oh, I understand. That's why it's completely impractical to fetch data from Scratch projects. I get it now!

**Comment by The-Cheese-Eater** [comment]
"Sorry, If I seemed like I was Bill Gates (I'm doing a play, I'm Bill Gates :3) I just thought it would be a cool thing to do" That's OK. :)

"Oh, I understand. That's why it's completely impractical to fetch data from Scratch projects. I get it now!" I don't see why you are so obsessed with the idea of fetching data from projects. The old SR didn't do that. It's just a pain in the rear-end to open up a new project and upload things to it, and then navigate to this site. With that idea, Scratch is basically a large warehouse, and OpenSprites is a small lean-to on one side. Scratch stores all the media, and OS just dishes it out. Honestly, get over the fact that it's completely impractical to fetch data from Scratch projects. I wouldn't want to faf around with uploading to projects. Perhaps suggest positive reasons for this idea??

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater I hate the project idea :P

**Comment by andrewjcole** [comment]
When I joined this thing, I was thinking of suggesting that as an alternative option, but no the main one.

**Comment by The-Cheese-Eater** [comment]
@andrewjcole The project idea is nice if you already have the media uploaded to a project, but if it was a main uploading method it would become a bit cumbersome. I agree with you in that there should be two ways of uploading stuff.

**Comment by GrannyCookies** [comment]
As an alt. method it'd be great, but we should work on the main method first.

**Comment by The-Cheese-Eater** [comment]
Agreed

**Comment by bleush38p** [comment]
OK. Scrap anything I've ever said before. Hear me out; I'll hear anything you'd like to say.

*bear with any mistakes I've made, doing this on a phone is awful*

As far as having assets to upload, I think there are two situations, and **each is equally likely.**

1: I created something on my computer. Maybe it was in offline Scratch, or maybe I used a graphics or sound editor. No matter; it's a sound or image or something. I go to OS, log in, and click create. I get two options, and choose "Upload from your computer." Now I upload, name, all that. Submit.

2: I created something in the Scratch editor. Maybe it's a script, or I've got a visual or sound I recorded or drew in Scratch. I think this option is going to be surprising popular. The old Scratch resources did not do this because it was not practical then - it *couldn't* effectively be done. Now, however, I think there is the framework already built to very easily do it. My plugin which does is nearing completion and I will happily speed up development efforts. I log in to OS, press Create, choose "Import from a Scratch project." I'm logged into OS, so it knows who I am on Scratch. I see my uploaded projects and can then go through the usual process. **The asset is then moved to OS, and stored the same way as any other.**

What I'm saying is really two things - 1) it's fine if we move things to OS storage; I think you guys are stressing about that without seeing the original essence of the idea, and 2) it's fine if there's a uploading choice, but importing shouldn't be given lower priority - i.e. I shouldn't have to click some 2pt size button, or hunt for some seeing to do it, or anything crazy like that.

**Comment by GrannyCookies** [comment]
@bleush38p That's... exactly what I invisioned.

**Comment by bleush38p** [comment]
Well, that's a thing :P

**Comment by The-Cheese-Eater** [comment]
I must say, I do like the idea of that. I think that would be a great route to take. Having the options side-by-side is good because the use can choose which one they like best, instead of a recommended one.
