### ISSUE TITLE
Colour theme

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#9]
We need to change the colour theme to look more like Scratch's. To be honest Scratch's colour theme is just blue, white and orange. :P

**Comment by liam4** [comment]
Sure, it's easy to change the theme I'm making. XD

**Comment by andrewjcole** [comment]
^^ You mean the one you'r working on with Cloud9?

**Comment by liam4** [comment]
@andrewjcole Yup.

**Comment by DM5555** [comment]
It can look BETTER than scratch's theme

**Comment by Rumanti** [comment]
Does it has to look like Scratch's theme? (or is it just me?)

**Comment by The-Cheese-Eater** [comment]
Well, we'd like it to be related to Scratch in some way. But it doesn't have to be an exact replica.

**Comment by jayforsythe** [comment]
I recently made a repo on my profile that mimics Scratch. I believe cheeseeater saw it.
I think it should look like Scratch's color theme. Otherwise, people will be obsessed with "flat design" and making it look "professional". We should settle for "kiddish" because we want the site to be for kids and not like Microsoft.

**Comment by The-Cheese-Eater** [comment]
Yep, and that is what we are doing. I'm editing your styling now to separate the navbar from the main page.

**Comment by jayforsythe** [comment]
Ok great!! :D

**Comment by GrannyCookies** [comment]
If you look at the site now, I've added all the new css etc.

**Comment by Rumanti** [comment]
Is it time to close this? (since we already redesigned the theme?)

**Comment by The-Cheese-Eater** [comment]
I guess so
